import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
import React, { useRef, useState } from 'react';
import { useClickAway } from 'react-use';
import historyList from '../data/historyList.json';

import Discord from '../assets/icons/discord.svg';
import Twitter from '../assets/icons/twitter.svg';
import Telegram from '../assets/icons/telegram.svg';
import Menu from '../assets/icons/menu.svg';

export const getRandomElementFromArray = (arr: any[]) => {
  const randomIndex = Math.floor(arr.length * Math.random());
  return arr[randomIndex];
};

const Home: NextPage = () => {
  const historyColors = ['#5B5B5B', '#86efac', '#4ade80', '#16a34a', '#166534'];
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const mobileNavigation = useRef(null);

  const profiles = [
    {
      title: 'Non-contributor',
      status: 'open to work (updated 1 year ago)',
      repositories: 5,
      followers: '2',
      jobOffers: 0,
      avatar: './non-contributor.jpg',
    },
    {
      title: 'Contribute3 member',
      status: 'Senior Software Engineer at Metaverse',
      repositories: 125,
      followers: '12k',
      jobOffers: 64,
      highlightOffers: true,
      hasAchievements: true,
      highlyEffective: true,
      avatar: './contribute3-member.jpg',
    },
  ];

  const chatExamples = [
    {
      title: 'Contribute & collaborate',
      messages: [
        {
          avatar: 'carrot.jpg',
          color: 'text-yellow-500',
          username: 'fake carrot',
          date: 'Today, 12:22',
          content: 'Hi guys. Opened an issue for hardhat-boilerplate for that deploy bug.<br><u>Can someone help me</u> with the testing part? <span class="text-sky-500">https://github.com/N...</a>',
        },
        {
          avatar: 'mumu.jpg',
          color: 'text-emerald-500',
          username: 'Mumu',
          date: 'Today, 13:54',
          content: 'Working on that module too, I\'ll check it tonight',
          isReply: true,
        },
      ],
    },
    {
      title: 'Meet people & join events',
      messages: [
        {
          avatar: 'krtek.jpg',
          color: 'text-pink-500',
          username: 'Krtek',
          date: 'Today, 01:02',
          content: 'Hi! <u>Looking for a team</u> for Polygon BUIDL IT. Good at React (ts+redux) and JS in general 🤓',
        },
        {
          avatar: 'mumu.jpg',
          color: 'text-indigo-500',
          username: 'Rust Magician',
          date: 'Today, 01:15',
          content: 'Yo! DM me, we were just looking for a frontend dev',
          isReply: true,
        },
      ],
    },
    {
      title: 'Grow skills & get help',
      messages: [
        {
          avatar: 'morti.jpg',
          color: 'text-yellow-500',
          username: 'Momento Morti',
          date: 'Today, 20:55',
          content: 'I am currently making a TLS client with Rust (OpenSSL). Having troubles with brotli compression.<br><u>Can anyone help?</u>',
        },
        {
          avatar: 'redstone.jpg',
          color: 'text-red-400',
          username: 'redstone guy',
          date: 'Today, 21:01',
          content: 'Made similar thing, here\'s the repo <span class="text-sky-500">https://github...</span>',
          isReply: true,
        },
      ],
    },
  ];

  useClickAway(mobileNavigation, () => {
    setIsMenuOpen(false);
  });

  return (
    <div>
      <Head>
        <title>Contribute3 — </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="container mx-auto px-4 py-6 flex items-center gap-4 sm:gap-12">
        <a href="/" className="font-mono text-primary font-bold text-xl">
          <img src="./logo.svg" className="h-10" alt="contribute3 logo" />
        </a>

        <div className="flex-1" />

        <nav className="hidden md:flex gap-8">
          <a className="text-white active:text-primary" href="#">Home</a>
          <a className="text-white active:text-primary" href="#">Explore projects</a>
          <a className="text-white active:text-primary" href="#">Blog</a>
        </nav>

        <div className="hidden md:flex gap-4">
          <a href="https://discord.gg/hCqtJHKQvu" target="_blank"
            className="text-white hover:text-emerald-400" rel="noreferrer"><Discord className="h-6 w-6" alt="" /></a>
          <a href="https://twitter.com/Contribute3HQ" target="_blank"
            className="text-white hover:text-emerald-400" rel="noreferrer"><Twitter className="h-6 w-6" alt="" /></a>
          <a href="https://contribute3.t.me/" target="_blank"
            className="text-white hover:text-emerald-400" rel="noreferrer"><Telegram className="h-6 w-6" alt="" /></a>
        </div>

        <div ref={mobileNavigation} className="md:hidden relative">
          <button onClick={() => setIsMenuOpen(!isMenuOpen)} type="button" className="p-0">
            <Menu />
          </button>
          <ul className={`${!isMenuOpen && 'hidden'} absolute z-10 divide-y divide-zinc-700 right-0 w-52 rounded-lg bg-zinc-800 text-left font-normal`}>
            <div>
              <li className="text-xs opacity-50 pt-4 pb-2 px-4">Navigation</li>
              <li><a className="text-white active:text-primary py-2 px-4 block" href="#">Home</a></li>
              <li><a className="text-white active:text-primary py-2 px-4 block" href="#">Explore</a></li>
              <li><a className="text-white active:text-primary py-2 px-4 block" href="#">Community</a></li>
            </div>
            <div>
              <li className="text-xs opacity-50 pt-4 pb-2 px-4">Join us</li>
              <li><a className="text-white active:text-primary py-2 px-4 block" href="https://discord.gg/hCqtJHKQvu" target="_blank" rel="noreferrer">Discord</a></li>
              <li><a className="text-white active:text-primary py-2 px-4 block" href="https://twitter.com/Contribute3HQ" target="_blank" rel="noreferrer">Twitter</a></li>
              <li><a className="text-white active:text-primary py-2 px-4 block" href="https://contribute3.t.me/" target="_blank" rel="noreferrer">Telegram</a></li>
            </div>
          </ul>
        </div>
      </header>

      <div className="container overflow-visible mx-auto px-4 my-16 sm:my-32 text-center relative">
        <img src="./blurry-gradient.png" className="blurry-gradient blurry-gradient--md -top-1/4 -left-1/4" alt="" />

        <div className="relative">
          <h1>Start working on web3 <br className="md:block hidden" />
        projects today.</h1>
          <p className="mt-6 opacity-70 sm:text-xl text-base leading-7 font-light">
          Community where developers collaborate on open-source web3 projects <br className="md:block hidden" />
          to gain real-world experience, improve tech skills and build professional network.
          </p>
          <div className="flex sm:gap-6 gap-4 mt-10 justify-center flex-wrap">
            <a href="https://discord.gg/hCqtJHKQvu" target="_blank" className="hover:no-underline" rel="noreferrer"><button className="bg-primary--darken">Join community</button></a>
            {/* <button><span className="text-primary">Explore projects</span></button> */}
          </div>
        </div>
      </div>

      <div className="container overflow-visible relative max-w-xl lg:max-w-6xl flex mx-auto px-4 gap-12 sm:gap-16 lg:gap-8 flex-col lg:flex-row">
        <img src="./blurry-gradient.png" className="blurry-gradient blurry-gradient--lg -right-20 sm:-right-48 -top-64" alt="" />

        {profiles.map((profile) => (
          <div key="" className={`lg:w-1/2 relative flex-wrap ${!profile.highlyEffective && 'opacity-50'}`}>
            <h3 className="font-bold">
              <span className={profile.highlyEffective ? 'text-primary' : ''}>
                {profile.title}
              </span>
            </h3>
            <div className="sm:mt-8 mt-4 flex gap-4 sm:gap-8">
              <div className="min-w-max">
                <img className="h-20 w-20 sm:h-32 sm:w-32 bg-white rounded-xl object-cover" src={profile.avatar} alt="" />

                {profile.hasAchievements && (
                  <div className="mt-4 hidden sm:flex">
                    <img
                      src="./github-achievements/0.png"
                      alt=""
                      className="w-12 h-12"
                    />
                    <img
                      src="./github-achievements/1.png"
                      alt=""
                      className="w-12 h-12 -ml-5"
                    />
                    <img
                      src="./github-achievements/2.png"
                      alt=""
                      className="w-12 h-12 -ml-5"
                    />
                    <img
                      src="./github-achievements/3.png"
                      alt=""
                      className="w-12 h-12 -ml-6"
                    />
                  </div>
                )}
              </div>

              <div className="text-sm sm:text-base">
                <p className="mt-1 mb-3"><b>Status:</b> {profile.status}</p>

                <div className="w-full max-w-xs flex flex-wrap gap-1 opacity-70">
                  {historyList.map((colorIndex) => (
                    <div key="" className="history-dot" style={{
                      background: profile.highlyEffective ? historyColors[colorIndex]
                        : historyColors[Math.max(colorIndex - 3, 0)],
                    }}></div>
                  ))}
                </div>

                <p className="mt-5"><b>{profile.repositories}</b> repositories · <b>{profile.followers}</b> followers</p>
                <p className={'mt-2 '}>
                  <span className={`${profile.jobOffers > 0 ? 'text-primary' : ''}`}><b>{profile.jobOffers}</b> job offers</span>
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* What we do */}

      <div className="blue-block relative my-16 sm:my-32">

        <div className="mx-auto max-w-2xl xl:container px-4 py-16 sm:py-32">

          <h2>What we do in <span className="text-primary">contribute3  </span></h2>

          <div className="flex flex-wrap xl:flex-nowrap gap-12 mt-10 align-top">
            {
              chatExamples.map((example) => (
                <div key="" className="xl:w-1/3">
                  {/* <h4><span className="text-primary">Contribute</span> & collaborate</h4> */}
                  <h4 className="text-primary">{example.title}</h4>

                  {example.messages.map((message) => (
                    <div key="" className={`mt-6 bg-discord p-4 flex gap-4 rounded-xl ${message.isReply && 'ml-10 sm:ml-20'}`}>
                      <img
                        className="w-12 h-12 bg-white rounded-full"
                        style={{ minWidth: '3rem' }}
                        src="./avatars/1.jpg"
                      />

                      <div>
                        <div>
                          <span className={`font-bold ${message.color}`}>{message.username}</span>
                          <span className="ml-2 opacity-50 text-sm">{message.date}</span>
                        </div>
                        <p className="mt-1" style={{ 'word-break': 'break-word' }} dangerouslySetInnerHTML={{ __html: message.content }}></p>
                      </div>
                    </div>
                  ))}

                  {/* <div className="ml-10 sm:ml-20 mt-6 bg-discord p-4 flex gap-4 rounded-xl">
                    <img
                      className="w-12 h-12 bg-white rounded-full"
                      style={{ minWidth: '3rem' }}
                      src="./avatars/2.jpg"
                    />

                    <div>
                      <div>
                        <span className="font-bold text-yellow-400">Alex</span>
                        <span className="ml-2 opacity-50 text-sm">Today, 12:22</span>
                      </div>
                      <p className="mt-1">
  Hi guys. Opened an issue for hardhat-boilerplate for that deploy.
                      </p>
                    </div>
                  </div> */}
                </div>
              ))
            }
          </div>

        </div>
      </div>

      <div className="container mx-auto px-4 my-16 sm:my-32">
        <h2>Not a <span className="text-primary">contributor</span>?</h2>
        <h4 className="opacity-50 mt-3 mb-10 sm:mb-20">Here&apos;s why you should become one</h4>

        <div className="flex flex-wrap md:flex-nowrap gap-4 md:gap-12 mt-8 sm:mt-16">
          <h3 className="md:w-1/2 text-right md:-mt-0.5">Why contribute:</h3>
          <ul className="md:w-1/2 leading-10 pl-4 md:pl-0 tick-list">
            <li>Build your job resume</li>
            <li>Grow your professional network</li>
            <li>Enhance your tech skills</li>
            <li>Meet people with same interests</li>
            <li>Find mentors and teach others</li>
          </ul>
        </div>

        <div className="flex flex-wrap md:flex-nowrap gap-4 md:gap-12 mt-8 sm:mt-16">
          <h3 className="md:w-1/2 text-right md:-mt-0.5">Why contribute:</h3>
          <ul className="md:w-1/2 leading-10 pl-4 md:pl-0 tick-list">
            <li>Build your job resume</li>
            <li>Grow your professional network</li>
            <li>Enhance your tech skills</li>
            <li>Meet people with same interests</li>
            <li>Find mentors and teach others</li>
          </ul>
        </div>
      </div>

      <div className="bg-primary-gradient hidden">
        <div className="container mx-auto px-4 py-20 flex items-center gap-8">
          <div className="w-2/3">
            <h2 className="text-5xl">Looking for a <span className="text-primary">web3 project</span> to contribute?</h2>
            <h4 className="mt-6">We made an list of cool
        web3 projects <br/> ranked by activity and tech stack</h4>

            <a href="#" className="mt-10 block">Check it out</a>
          </div>

          <img src="" alt="" className="bg-white w-96 h-72" />
        </div>
      </div>

      <div className="blue-block mt-16 sm:mt-32">
        <div className="container mx-auto px-4 py-16 sm:py-32">
          <h1 className="text-center">Are you with us?</h1>
          <p className="mt-3 text-center opacity-50 text-md sm:text-lg">Membership is free. As all best things in life.</p>

          <div className="flex flex-wrap gap-4 mt-8 sm:mt-16 justify-center">
            <a href="#" className="block text-center hover:no-underline">
              <button className="text-sky-400">
                <Telegram height={20} />
            Telegram
              </button>
            </a>

            <a href="#" className="block text-center hover:no-underline">
              <button className="text-indigo-400">
                <Discord height={20} />
            Discord
              </button>
            </a>

            <a href="#" className="block text-center hover:no-underline">
              <button className="text-sky-500">
                <Twitter height={20} />
            Twitter
              </button>
            </a>
          </div>
        </div>
      </div>

      <footer className="container mx-auto text-center text-xs my-8 font-mono">
          made by <a href="https://twitter.com/gssvv_" target="_blank" rel="noreferrer">@gssvv_</a>
      </footer>
    </div>
  );
};

export default Home;
